// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/physicist2018/url-shortener-go/internal/domain"
)

// MockURLLinkServicer is a mock of URLLinkServicer interface.
type MockURLLinkServicer struct {
	ctrl     *gomock.Controller
	recorder *MockURLLinkServicerMockRecorder
}

// MockURLLinkServicerMockRecorder is the mock recorder for MockURLLinkServicer.
type MockURLLinkServicerMockRecorder struct {
	mock *MockURLLinkServicer
}

// NewMockURLLinkServicer creates a new mock instance.
func NewMockURLLinkServicer(ctrl *gomock.Controller) *MockURLLinkServicer {
	mock := &MockURLLinkServicer{ctrl: ctrl}
	mock.recorder = &MockURLLinkServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLLinkServicer) EXPECT() *MockURLLinkServicerMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockURLLinkServicer) CreateShortURL(ctx context.Context, longURL string) (*domain.URLLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", ctx, longURL)
	ret0, _ := ret[0].(*domain.URLLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockURLLinkServicerMockRecorder) CreateShortURL(ctx, longURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockURLLinkServicer)(nil).CreateShortURL), ctx, longURL)
}

// GetOriginalURL mocks base method.
func (m *MockURLLinkServicer) GetOriginalURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockURLLinkServicerMockRecorder) GetOriginalURL(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockURLLinkServicer)(nil).GetOriginalURL), ctx, shortURL)
}

// Ping mocks base method.
func (m *MockURLLinkServicer) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLLinkServicerMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLLinkServicer)(nil).Ping), ctx)
}
